---
name: CRON Trigger devel images

on:
  schedule:
  - cron:  '0 3 * * *'
  push:
    branches:
    - master
    paths:
      'ros2/source/**'
jobs:
  source_build:
    name: Trigger devel image
    env:
      dockerTag: ${{ 'devel' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Call devel webhook
      run: |
        echo "coucou"
